[[redirects]]
  from = "/"
  to = "/en/"
  conditions = { Language = ["en"] }
  status = 302

[[redirects]]
  from = "/"
  to = "/ru/"
  status = 302

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "connect-src https:; object-src 'none'; frame-ancestors 'none'; form-action 'none'; base-uri 'none'"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"